---
#### begin checking app change

- import_tasks: check_bas_app.yml
  when: (inventory_hostname in groups['APP'])
  tags:
    - change_inspection

- import_tasks: check_dxs_app.yml
  when: (inventory_hostname in groups['IMT'])
  tags:
    - change_inspection

- import_tasks: check_ngx_app.yml
  when: (inventory_hostname in groups['NGX'])
  tags:
    - change_inspection

#### finish checking app change
