---
#### begin updating app
- name: start update app
  block:
  #bas_app_postrade
    - import_tasks: update_app.yml
      when: inventory_hostname in groups['APP']
      tags:
      - update_APP
#### finish updating app
