---  
#### begin checking  NGX update
- name: GET OUT NGX V{{version}} update file
  stat: 
    path: "{{ansible_env.HOME}}/app/rg"
  register: ngx_file

- name: start update OUT NGX
  block:
    #### begin updating postarde
    - name: update OUT NGX project
      debug:
        msg: "LOG INFO: begin updating OUT NGX project. "

    - name: create srcipt sh
      file:
        path: "{{ansible_env.HOME}}/allBin"
        state: directory  

    - name: copy update file 
      copy:
        src: ptps_ngx.zip
        dest: "{{ansible_env.HOME}}/allBin/ptps_ngx.zip" 

    - name: update ngx app add script
      shell: |
        unzip -o {{ansible_env.HOME}}/allBin/ptps_ngx.zip -d {{ansible_env.HOME}}/allBin/
        rm -rf {{ansible_env.HOME}}/allBin/ptps_ngx.zip
        sed -i '/listen/a\        if ($request_method !~ ^(GET|HEAD|POST)$ ) {\n           return 444;\n        }' /home/ptd/app/rg/conf/nginx.conf
        #bengkuizhong......
        sed -i '/default_type/a\    client_body_timeout 10;\n    client_header_timeout 10;\n    send_timeout 10;\n    autoindex off;' /home/ptd/app/rg/conf/nginx.conf
        sed -i "/worker_processes/i user  nobody;" /home/ptd/app/rg/conf/nginx.confd 
        #add crontab
        (crontab -l; echo -e "0 0 * * * sh /home/ptd/allBin/nginx_logs.sh") |crontab -
        (crontab -l; echo -e "0 1 * * * sh /home/ptd/allBin/cleanLogs_linux.sh 30") |crontab -
        #user noboay
        sed -i '/worker_processes/i user  nobody;' /home/ptd/app/rg/conf/nginx.conf 

    #提示升级结果
    - name: show OUT NGX process info
      debug:
        msg: "LOG INFO: update OUT NGX services succeed. "
    
  when: ngx_file.stat.exists
#### finish updating app
