---  
#### begin checking  APP_postrade update
- name: GET out_postrade V{{version}} update file
  stat: 
    path: "{{ansible_env.HOME}}/upgrade/deploy/V{{version}}/app/postrade"
  register: postrade_app_file

- name: copy out cleanLogs_linux.sh file
  copy:
    src: cleanLogs_linux.sh
    dest: "{{ansible_env.HOME}}/allBin/cleanLogs_linux.sh"
  
- name: start update out_postrade
  block:
    #### begin updating postarde
    - name: update out_postrade project
      debug:
        msg: "LOG INFO: begin updating out_postrade project. "

    #先删除目录   
    - name: delete postarde deploy directory  
      file:
        path: "{{ansible_env.HOME}}/app/postrade/deploy"
        state: absent
        
    #再创建目录  
    - name: create postrade deploy directory
      file:
        path: "{{ansible_env.HOME}}/app/postrade/deploy"
        state: directory 
    
    #全量升级postrade工程
    - name: update out_postrade
      shell: |
        unzip -o {{ansible_env.HOME}}/upgrade/deploy/V{{version}}/app/postrade/postrade.war -d {{ansible_env.HOME}}/app/postrade/deploy
        #get out dxs ip
        imt_ip_master=`cat /home/ptd/app/postrade/config/postrade.properties|grep ^application.ServerAddress|awk -F "=" '{print $5}'|awk -F ")" '{print $1}'`
        imt_ip_slave=`cat /home/ptd/app/postrade/config/postrade.properties|grep ^application.ServerAddress|awk -F "=" '{print $8}'|awk -F ")" '{print $1}'`
        #update postrade.properties
        sed -i "s/application.ServerAddress=.*/application.ServerAddress=(ADDRESS_LIST=(ADDRESS=(IP=${imt_ip_master})(PORT=61616)(USER=ptrd)(PASSWORD=Ptrd_0617))(ADDRESS=(IP=${imt_ip_slave})(PORT=61616)(USER=ptrd)(PASSWORD=Ptrd_0617)))/g" /home/ptd/app/postrade/config/postrade.properties
        sed -i "s/application_outer.ServerAddress=.*/application_outer.ServerAddress=(ADDRESS_LIST=(ADDRESS=(IP=${imt_ip_master})(PORT=61616)(USER=ptrd)(PASSWORD=Ptrd_0617))(ADDRESS=(IP=${imt_ip_slave})(PORT=61616)(USER=ptrd)(PASSWORD=Ptrd_0617)))/g" /home/ptd/app/postrade/config/postrade.properties
        #add cert get old value
        key_pwd_value=`cat /home/ptd/app/postrade/deploy/WEB-INF/classes/resources/spring/applicationContext-SysInfo.xml |grep -A 1 privateKeyPassword|grep value|awk -F ">" '{print $2}'|awk -F "<" '{print $1}'`
        echo "ptrd.privateKeyPassword=${key_pwd_value}" >>/home/ptd/app/postrade/config/postrade.properties
        #update crontab
        crontab -l >v615.crontab
        sed -i "/clenLog.sh/d" v615.crontab
        crontab -r && crontab v615.crontab
        (crontab -l; echo -e "5 4 * * * . /etc/profile;sh /home/ptd/allBin/cleanLogs_linux.sh 30") |crontab -

    #升级中间件
    - name: copy web.xml file 
      copy:
        src: web.xml
        dest: "{{ansible_env.HOME}}/upgrade/deploy/V{{version}}/app/web.xml" 
    #update web.xml
    - name: update web.xml
      shell: |
        cp -r {{ansible_env.HOME}}/upgrade/deploy/V{{version}}/app/web.xml /home/ptd/tomcat7_postrade/conf/
        cp -r {{ansible_env.HOME}}/upgrade/deploy/V{{version}}/app/web.xml /home/ptd/tomcat7_cometDServer/conf/
    
    #update config
    - name: update config
      shell: |
        source /etc/profile
        set -m;sh /home/ptd/allBin/update_config.sh
    #提示升级结果
    - name: show out_postrade process info
      debug:
        msg: "LOG INFO: update out_postrade services succeed. "
    
  when: postrade_app_file.stat.exists
#### finish updating app
