---
#### begin archive  postrade   files
- name: get out postrade_process V{{version}} archive files
  stat: 
    path: "{{ansible_env.HOME}}/upgrade/deploy/V{{version}}/app/postrade"
  register: postrade_archive

#如果目录不存在
- name: check out postrade V{{version}} backup directory
  debug: 
    msg: "LOG: not involved out postrade update."
  when: postrade_archive.stat.exists == False

#### begin archive files

- name: start archiving out postrade files
  block:
    - name: show out postrade process info
      debug:
        msg: "LOG INFO: begin archiving out postrade files ."

    - name: archiving out postrade files .......
      shell: |
        ls | grep -v {{version}} |xargs rm -rf 
      args:
        chdir: "{{ansible_env.HOME}}/app/postrade/backup"

    - name: show out postrade process info
      debug:
        msg: "LOG INFO: archiving out postrade succeed."
    
  when: postrade_archive.stat.exists

#### finish archive postrade files