---
#### begin archive  out ngx  files
- name: get out ngx V{{version}} archive files
  stat: 
    path: "{{ansible_env.HOME}}/var/backup/"
  register: postrade_archive

#如果目录不存在
- name: check out ngx V{{version}} backup directory
  debug: 
    msg: "LOG: not involved out ngx update."
  when: postrade_archive.stat.exists == False

#### begin archive files

- name: start archiving out ngx files
  block:
    - name: show out ngx process info
      debug:
        msg: "LOG INFO: begin archiving out ngx files ."

    - name: archiving out ngx files .......
      shell: |
        ls | grep -v {{version}} |xargs rm -rf 
      args:
        chdir: "{{ansible_env.HOME}}/var/backup/"

    - name: show out ngx process info
      debug:
        msg: "LOG INFO: archiving out ngx succeed."
    
  when: postrade_archive.stat.exists

#### finish archive out ngx files