---
#### begin archiveing old files
- name: show process info
  debug:
    msg: "LOG INFO begin archiving files ...... "
  tags:
    - archive_files

#### begin archive files ......
#app
- import_tasks: archive_app.yml
  when: (inventory_hostname in groups['APP'])
  tags:
    - archive_files

#### finish archive files ......
