
- name: check record dir
  stat:
    path: "/home/appspt/Version"
  register: record_dir
  
- name: create record dir
  fail: 
    msg: "ERROR: check dir!"
  when: record_dir.stat.exists == False
  
- name: check record detail file
  stat:
    path: "/home/appspt/Version/{{appName}}.info"
  register: record_detail


- name: check record detail file to ansible
  stat:
    path: "/home/appspt/Version/{{release_env}}_{{appName}}.info"
  register: record_detail_ansible
  connection: local
  
- name: create record detail
  shell: |
    >  "{{appName}}.info"
    echo "NULL" >  "{{appName}}.ver"
  args:
    chdir: "/home/appspt/Version"
  when: record_detail.stat.exists == False


- name: create record detail to ansible
  shell: |
    _date="`date \"+%Y%m%d %H:%M:%S\"`";
    echo "{{ansible_default_ipv4.address}} {{ansible_hostname}} ${_date} {{ansible_hostname}} CFETS-APP {{appName}}" NULL>>  "{{release_env}}_{{appName}}.ver"
  args:
    chdir: "/home/appspt/Version"
  when: record_detail_ansible.stat.exists == False
  connection: local



- name: get current version 
  shell: |
    cat {{appName}}.ver | tail -1 | awk '{print$5}'
  args:
    chdir: "/home/appspt/Version"
  register: current_ver
  when: buildstate == "Update"
 
- name: get update version
  shell: |
    echo -n  "{{version}}" | awk -F'_' '{print$1}'
  args:
    chdir: "/home/appspt/Version"
  register: ver


- name: get three bit version
  shell: |
    echo -n {{ver.stdout}} | awk -F '.' '{print$1"."$2"."$3}'
  register: ver3


- name: check detail process
  shell: |
    cat  {{appName}}.ver | grep {{ver3.stdout}} | tail -1;
  args:
    chdir: "/home/appspt/Version"
  register: ver3process


- name: record detail info
  shell: |
    _date="`date \"+%Y%m%d %H:%M:%S\"`";
    c_ver="{{current_ver.stdout}}"
    if [ "{{current_ver.stdout}}" == "" ] ; then c_ver="NULL"; fi;
    echo "${_date} CFETS-APP {{appName}} Update V{{ver.stdout}}" >> "{{appName}}.info"
    echo "${_date} CFETS-APP {{appName}} {{buildstate}} from ${c_ver} to V{{ver3.stdout}} is succeed" >> "{{appName}}.info"
  args:
    chdir: "/home/appspt/Version"

- name: record detail info
  shell: |
    _date="`date \"+%Y%m%d %H:%M:%S\"`";
    c_ver="{{current_ver.stdout}}"
    if [ "{{current_ver.stdout}}" == "" ] ; then c_ver="NULL"; fi;
    echo "{{ansible_default_ipv4.address}} {{ansible_hostname}} ${_date} CFETS-APP {{appName}} Update V{{ver.stdout}}" >> "{{release_env}}_{{appName}}.info"
    echo "{{ansible_default_ipv4.address}} {{ansible_hostname}} ${_date} CFETS-APP {{appName}} {{buildstate}} from ${c_ver} to V{{ver3.stdout}} is succeed" >> "{{release_env}}_{{appName}}.info"
  args:
    chdir: "/home/appspt/Version"
  connection: local

- name: record ver3 process
  shell: |
    _date="`date \"+%Y%m%d %H:%M:%S\"`";
    echo "${_date} CFETS-APP {{appName}} V{{ver3.stdout}}" >> "{{appName}}.ver"
  args:
    chdir: "/home/appspt/Version"
  when: ver3process.stdout == '' 
    

- name: record ver3 process to ansible 
  shell: |
    _date="`date \"+%Y%m%d %H:%M:%S\"`";
    echo "{{ansible_default_ipv4.address}} {{ansible_hostname}} ${_date} CFETS-APP {{appName}} V{{ver3.stdout}}" >> "{{release_env}}_{{appName}}.ver"
  args:
    chdir: "/home/appspt/Version"
  when: ver3process.stdout == ''
  connection: local

